# import the standard google genertive ai python package 
import google.generativeai as genai

# load environmental variables from .env file 
from dotenv import load_dotenv
load_dotenv()

import streamlit as st
# import os so that we can work with the operating system 
import os

# configure the generative AI model with the API key
my_api = os.environ.get('GOOGLE_API_KEY')
genai.configure(api_key = my_api)

model = genai.GenerativeModel('gemini-1.5-flash')

def get_gemini_response(question):
    response = model.generate_content(question)
    return response.text

# initialize the streamlit app
st.set_page_config(page_title = 'Gemini Powered Bot', page_icon = ':ballon')

st.title('Welcome to Gemini Powered Bot')

user_quest = st.text_input('Write Your question here...', placeholder ='Type here')
btn = st.button('Send')

if btn and not user_quest:
    st.info('Please enter your question and click the send button below')

if user_quest and btn:
    answer = get_gemini_response(user_quest)
    st.subheader("Answer:")
    st.write(answer) 

else:
    st.markdown('<div style="height: 300px;"></div>', unsafe_allow_html=True) 
    st.info('This bot uses the Google\'s Generative AI model, gemini-1.5-flash, developed by Kaletsidik. The model generates text based on the given input. The text generated by the model is not guaranteed to be accurate or helpful. If you need help with a specific issue, feel free to ask.')
    st.markdown('---')
    st.success("Made By Kaletsidik ©2024")